version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .dbenv


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/html/static/
      - media_files:/var/html/media
    depends_on:
      - auth


  redis:
    container_name: auth_redis
    image: redis:7.2-rc-alpine
    restart: always


  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    restart: always


  auth:
    build: .
    container_name: auth_fastapi
    depends_on:
      - db
      - redis
    ports: 
      - "8080:8080"
    env_file:
      - .env
      - .env1
      - .env2
      - .env3


volumes:
  static_files:
  media_files:
