"""empty message

Revision ID: b7e36b69e8af
Revises: 7b1c9288cf29
Create Date: 2024-02-13 23:12:55.845329

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7e36b69e8af'
down_revision: Union[str, None] = '7b1c9288cf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_token', ['uuid'])
    op.create_unique_constraint(None, 'roles', ['uuid'])
    op.create_unique_constraint(None, 'user_roles', ['uuid'])
    op.create_unique_constraint(None, 'users', ['uuid'])
    op.create_unique_constraint(None, 'users_sign_in', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_sign_in', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    # ### end Alembic commands ###
