version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:3.11.18
    ports:
      - "15672:15672"
      - "5672:5672"

  db_notify:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env_postgres_db

  
  gate_api:
    build: ../gate_api
    restart: always
    ports: 
      - "8082:8082"
    depends_on:
      - db_notify


  admin_postman:
    build: ../admin_postman
    restart: always
    ports: 
      - "8010:8010"
    volumes:
     - static_files:/app/static


  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  worker_sender:
    build: ../workers/sender
    restart: always
    depends_on:
      - rabbitmq
      - db_notify
      - mailhog


  worker_former:
    build: ../workers/former
    restart: always
    depends_on:
      - rabbitmq
      - db_notify
      - mailhog


  db_1:
    image: postgres:13.0-alpine
    ports:
      - 5442:5432
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env_db

  
  redis:
    container_name: movie_redis_1
    image: redis:7.2-rc-alpine
    restart: always


  auth_1:
    build: ../auth-service
    container_name: auth_1
    depends_on:
      - db_1
      - redis
    ports: 
      - "8081:8081"
    env_file:
      - .env_auth_db
      - .env_auth_fastapi
      - .env_redis
      - .env_auth_ya


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/html/static/
      - media_files:/var/html/media
    depends_on:
      - admin_postman

  scheduler_django:
    build: ../admin_postman
    command: celery -A admin_postman worker --loglevel=info
    volumes:
      - static_files:/app/static
    depends_on:
      - admin_postman
    environment:
      - DJANGO_SETTINGS_MODULE=admin_postman.settings
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq

  scheduler_checker:
    build: ../schedulers/checker
    restart: always
    depends_on:
      - rabbitmq
      - db_notify
    volumes:
      - .:/app
    command: celery -A tasks worker --beat -l info


volumes:
  static_files:
  media_files: