# Generated by Django 5.0.3 on 2024-04-01 13:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
