# Generated by Django 5.0.3 on 2024-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_emailcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='duration',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='periodicity',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('OT', 'Once')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
