# Generated by Django 5.0.3 on 2024-04-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_emailcampaign_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcampaign',
            old_name='user_gropus',
            new_name='user_groups',
        ),
    ]
