# Generated by Django 5.0.3 on 2024-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_rename_user_gropus_emailcampaign_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='sender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
